# Configuration file
LOG_FILE = 'PVCharge.log'
LOG_LEVEL = "INFO"        # Default INFO, change to DEBUG to diagnose issues

# MQTT Control topics
TOPIC_PREVENT_NON_SOLAR_CHARGE = "topic_base/prevent_non_solar_charge"
TOPIC_TESLAMATE_GEOFENCE =       "teslamate/cars/$car_id/geofence"
TOPIC_TESLAMATE_PLUGGED_IN =     "teslamate/cars/$car_id/plugged_in"
TOPIC_TESLAMATE_BATTERY_LEVEL =  "teslamate/cars/$car_id/battery_level"
# MQTT Status topics
TOPIC_STATUS =      "topic_base/status"
TOPIC_CHARGE_RATE = "topic_base/new_charge_rate"

# Control loop parameters
SLOW_POLLING = 30        # Charging disabled, control topic check interval (seconds)
SLOW_POLLING_CHK = 5     # Charging disabled, prevent non-solar charge check interval (seconds)
FAST_POLLING = 1         # Charging enabled, update rate (seconds)
MIN_CHARGE = 7           # Slowest allowed charge rate (Amps)
MAX_CHARGE_LIMIT = 80    # Max charge limit (%)
