# Configuration file
LOG_FILE = 'PVCharge.log'           # Log file name to use
LOG_LEVEL = "INFO"                  # Default INFO, change to DEBUG to diagnose issues
PREVENT_NON_SOLAR_CHARGE = "False"  # Default for after-hours charging, unless changed via MQTT
ENABLE_TESLA_PROXY = "False"        # Optionally enable TeslaBleHttpProxy (requires additional parameter in .env, and a running proxy)

# MQTT Control topics
TOPIC_PREVENT_NON_SOLAR_CHARGE =   "topic_base/prevent_non_solar_charge"
TOPIC_CHARGE_DELAY =               "topic_base/charge_delay"    # Commands: "delay" = delay charge for 1 hour, ## = minutes to delay charge, (other text, i.e. "cancel") = resume normal charge
TOPIC_TESLAMATE_GEOFENCE =         "teslamate/cars/$car_id/geofence"
TOPIC_TESLAMATE_PLUGGED_IN =       "teslamate/cars/$car_id/plugged_in"
TOPIC_TESLAMATE_BATTERY_LEVEL =    "teslamate/cars/$car_id/battery_level"
TOPIC_TESLAMATE_CHARGE_LIMIT_SOC = "teslamate/cars/$car_id/charge_limit_soc"
TOPIC_TESLAMATE_STATE =            "teslamate/cars/$car_id/state"
# MQTT Status topics
TOPIC_STATUS =                "topic_base/status"
TOPIC_CHARGE_RATE =           "topic_base/new_charge_rate"
TOPIC_CAR_NOT_HOME =          "topic_base/car_not_home"
TOPIC_CHARGING_STATE =        "topic_base/charging_state"
TOPIC_CHARGE_PORT_DOOR_OPEN = "topic_base/charge_port_door_open"
TOPIC_CHARGE_LIMIT_SOC =      "topic_base/charge_limit_soc"
TOPIC_BATTERY_LEVEL =         "topic_base/battery_level"

# Control loop parameters
MIN_CHARGE = 7           # Slowest allowed charge rate (Amps)
MIN_SOLAR = 500          # Minimum generation to enable polling (Watts)
SLOW_POLLING = 120       # Charging disabled, control topic check interval (seconds)
FAST_POLLING = 2         # Charging enabled, loop delay (seconds)
DELAYED_START_TIME = 10	 # When Energy is Available how long do we wait before starting charge (seconds)
DELAYED_STOP_TIME = 90   # When Available Energy is Reduced how long do we wait before stopping charge (seconds)
REPORT_DELAY = 60        # Send status string to MQTT every x (seconds)
HOME_TIMEOUT = 600       # How long after last contact until we consider car not Home (seconds)
