# Configuration file
LOG_FILE = 'PVCharge.log'           # Log file name to use
LOG_LEVEL = "INFO"                  # Default INFO, change to DEBUG to diagnose issues
PREVENT_NON_SOLAR_CHARGE = "False"  # Default for after-hours charging, unless changed via MQTT

# MQTT Control topics
TOPIC_PREVENT_NON_SOLAR_CHARGE = "topic_base/prevent_non_solar_charge"
TOPIC_TESLAMATE_GEOFENCE =       "teslamate/cars/$car_id/geofence"
TOPIC_TESLAMATE_PLUGGED_IN =     "teslamate/cars/$car_id/plugged_in"
TOPIC_TESLAMATE_BATTERY_LEVEL =  "teslamate/cars/$car_id/battery_level"
TOPIC_TESLAMATE_STATE =          "teslamate/cars/$car_id/state"
# MQTT Status topics
TOPIC_STATUS =      "topic_base/status"
TOPIC_CHARGE_RATE = "topic_base/new_charge_rate"

# Control loop parameters
MIN_CHARGE = 7           # Slowest allowed charge rate (Amps)
MAX_CHARGE_LIMIT = 80    # Max charge limit (%)
SLOW_POLLING = 30        # Charging disabled, control topic check interval (seconds)
SLOW_POLLING_CHK = 5     # Charging disabled, prevent non-solar charge check interval (seconds)
FAST_POLLING = 1         # Charging enabled, loop delay (seconds)
DELAYED_START_TIME = 10	 # When Energy is Available how long do we wait before starting charge (seconds)
DELAYED_STOP_TIME = 90   # When Available Energy is Reduced how long do we wait before stopping charge (seconds)
REPORT_DELAY = 60        # Send status string to MQTT every x (seconds), delayed by as much as SLOW_POLLING_CHK when charging disabled
